---
apiVersion: v1
kind: Service
metadata:
  name: {{build.name}}
  # {%- if "endpoint" in build.profile %}
  # annotations:
  #   getambassador.io/config: |
  #     ---
  #     apiVersion: ambassador/v0
  #     kind: Mapping
  #     name: {{build.name}}-mapping
  #     prefix: {{build.profile.endpoint}}
  #     service: {{build.name}}
  #     {%- if "weight" in build.profile %}
  #     weight: {{build.profile.weight}}
  #     {%- endif %}
  # {%- endif %}
spec:
  selector:
    app: {{build.name}}
  ports:
    - port: 80
      targetPort: http-api
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-config
data:
  USE_DOCKER: "yes"
  DATABASE_URL: "postgres://postgres:password@postgres:5432/djangoapp"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  REDIS_URL: "redis://redis:6379/0"
  CELERY_FLOWER_USER: "hwgCjZujIPKmxOMruhFGaQblJLzRMXad"
  CELERY_FLOWER_PASSWORD: "P6G16HcONxKAVzDQLH5ATVrlAbRtvAI4WcXhRsozP7yRUH5hiraUUqfVswhBb1j2"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{build.name}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{build.name}}
    spec:
      containers:
      - name: {{build.name}}
        image: {{build.images["Dockerfile"]}}
        imagePullPolicy: Always
        resources:
          requests:
            memory: 0.1G
            cpu: 0.1
          limits:
            memory: {{build.profile.max_memory}}
            cpu: {{build.profile.max_cpu}}
        ports:
        - name: http-api
          containerPort: 8000
        envFrom:
         - configMapRef:
             name: local-config
